### ISSUE TITLE
Missing ember-progress-bar dependency

### ISSUE THREAD

**Issue by AndreJoaquim** [uniplaces/ember-cli-uniq#208]
There's missing the dependency for `ember-progress-bar` which broke the `spa-offer-page` when I removed this addon from that project.

Similarly to the `ember-responsive`, `ember-progress-bar` should be installed when someone installs this addon using `ember install ember-cli-uniq`

**Comment by migueldemoura** [comment]
Fixed by: https://github.com/uniplaces/ember-cli-uniq/pull/295.
